### ISSUE TITLE
AttributeError: module 'dfxml' has no attribute 'XMLNS_DFXML'

### ISSUE THREAD

**Issue by dd388** [cul-it/hfs2dfxml#6]
This error is specific to BitCurator.

```
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import hfs2dfxml
>>> print(hfs2dfxml.DFXML)
<module 'Objects' from 'dfxml/python/Objects.py'>
>>> print(hfs2dfxml.DFXML.dfxml)
<module 'dfxml' from '/usr/local/lib/python3.5/dist-packages/bctools-1.7.36-py3.5.egg/dfxml.py'>
>>> 
```

**Fix**: Get dfxml module to be imported from ./dfxml/python/dfxml.py instead of bctools in this case

**Comment by kamwoods** [comment]
Oh dear, that dfxml.py somehow never got updated in the bctools core. The dfxml.py file really shouldn't be "installed" as part of a package by bctools, in any case...needs to be fixed. Either way, the default dfxml.py in BitCurator will be updated in the next release.

**Comment by kamwoods** [comment]
The outdated script has now been updated in the BitCurator repo, and will appear in the next production release (expected 11/11/2016).

**Comment by dd388** [comment]
Thanks, Kam! I'll test it out with my code and let you know how it goes.
